#pragma once
#include <llvm/IR/DIBuilder.h>
#include <llvm/IR/IRBuilder.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>

/**
 * Structure that contains all the LLVM 
 * context of a program generated by the compiler
 */
struct CodegenContext {
	///
	llvm::LLVMContext IRContext;

	///
	llvm::IRBuilder<> IRBuilder;

	///
	std::unique_ptr<llvm::Module> IRModule;

	/**
	 * Builder and module set up
	 */
	CodegenContext()
		: IRBuilder(IRContext), 
		  IRModule(std::make_unique<llvm::Module>("program", IRContext))
	{}
};
