#pragma once
#include <llvm/IR/IRBuilder.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>

/**
 * Structure that contains all the LLVM 
 * context of a program generated by the compiler
 */
struct CodegenContext {
	/// @brief Contexto de LLVM
	llvm::LLVMContext IRContext;

	/// @brief Builder de IR
	llvm::IRBuilder<> IRBuilder;

	/// @brief Modulo del programa a generar
	std::unique_ptr<llvm::Module> IRModule;

	/**
	 * @brief Generación del modulo y paso del contexto al builder
	 */
	CodegenContext()
		: IRBuilder(IRContext), 
		  IRModule(std::make_unique<llvm::Module>("program", IRContext))
	{}
};
